ArduPilot/UAVLogViewer

index.html, package-lock.json, src/App.vue, src/components/Home.vue, src/components/PlotSetup.vue, src/components/SideBarFileManager.vue, src/components/Sidebar.vue, src/main.js
Removed useless code  and made some design changes ;)
=> CSS cleanup/fixes

src/components/CesiumViewer.vue, src/components/Home.vue, src/components/PlotSetup.vue, src/components/SideBarFileManagerProgressBar.vue, src/components/Sidebar.vue
_This fixes responsiveness and implement a simple light mode (looking to improve it soon)_
=> Responsiveness fixes / Simple Light Mode

src/components/SideBarMessageMenu.vue, src/components/Sidebar.vue
=> Fix search box css

patches/plotly.js+1.49.0.patch
=> update plotly.js patch to fix bad time output

src/components/Globals.js, src/components/Home.vue, src/components/SideBarFileManager.vue, src/tools/dataflashDataExtractor.js, src/tools/mavlinkDataExtractor.js, src/tools/paramseeker.js, src/tools/parsers/dataflashParser.js, src/tools/parsers/mavlinkParser.js, test/unit/specs/dataflashlogs.spec.js, test/unit/specs/mavlinklogs.spec.js
=> Refactor home.vue so the data is extracted by specialized modules, add tests

build/webpack.base.conf.js, src/components/CesiumViewer.vue, src/components/PlotSetup.vue, src/components/Plotly.vue, src/tools/parsers/dataflashParser.js, src/tools/parsers/mavlinkParser.js
still not sure about making them fail the tests, will think about it
=> Fix Eslint errors, enable eslint checks in CI

src/components/Home.vue
=> Home: do not set show_map when receiving messages

src/components/PlotSetup.vue, src/components/Plotly.vue, src/components/SideBarMessageMenu.vue, src/components/widgets/TreeMenu.vue
=> Allow saving presets for the plots

src/assets/mavgraphs.xml, src/assets/parse_mavgraph.py, src/components/SideBarMessageMenu.vue
=> add some presets based on mavgraph.xml

src/components/Sidebar.vue
@biakp I could usse some help centering the icon there, and maybe with the media queries :grimacing:
=> Get widgets to their own menu

src/components/SideBarMessageMenu.vue
=> SideBarMessageMenu: sort messages

src/components/Home.vue, src/components/Sidebar.vue
=> Sidebar,Home: Move to plot view as soon as all data is extracted

src/components/Plotly.vue
=> Plotly: reset axis when removing plot

src/components/SideBarMessageMenu.vue
=> SideBarMessageMenu: fix search behavior

src/components/Plotly.vue
=> Plotly: Improve regex to correctly match XKF3.IYAW

src/tools/dataflashDataExtractor.js
=> DataflashExtractor: fix source of radians() function

test/unit/specs/dataflashlogs.spec.js, test/unit/specs/mavlinklogs.spec.js
this helps running the tests locally
=> Tests: find files locally AND at /tmp

src/components/Globals.js, src/components/PlotSetup.vue, src/components/Plotly.vue
=> Plotly, PlotSetup: display errors of evaluating expressions

src/tools/parsers/dataflashParser.js
=> DataflashParser: Fix gps time calculation

.github/workflows/nodejs.yml, test/unit/specs/dataflashlogs.spec.js
=> CI: change chrome download url and relax tests

src/components/PlotSetup.vue, src/components/SideBarMessageMenu.vue, src/components/Sidebar.vue
=> Custom preset trash button fix

build/webpack.dev.conf.js, config/index.js, src/assets/ekf3Graphs.xml, src/assets/ekfGraphs.xml, src/assets/mavgraphs2.xml, src/components/Plotly.vue, src/components/SideBarMessageMenu.vue, src/tools/parsers/dataflashParser.js, src/tools/parsers/parser.worker.js
=> Add support for instances in dataflash logging (plus a few extras)

src/components/Sidebar.vue
=> Add icon to Wiki, update repo to point to ardupilot

src/components/SideBarMessageMenu.vue
=> SideBarMessageMenu: remote STAT from blacklist filter

src/components/Globals.js, src/components/Plotly.vue, src/components/SideBarFileManager.vue, src/components/Sidebar.vue
=> Show the name of the current file

src/components/Plotly.vue
=> Plotly: no longer interpolate distant points

src/components/widgets/AttitudeWidget.vue, src/components/widgets/MessageViewer.vue, src/components/widgets/ParamViewer.vue, src/components/widgets/TxInputs.vue
added a css prop to stop the selection of text on the draggable components in the side panel
=> adding css property to stop the selection of text on the drag

src/components/widgets/AttitudeWidget.vue
=> AttitudeWidget: Fix attitude directions

src/components/CesiumViewer.vue, src/components/Plotly.vue, src/components/SideBarFileManager.vue, src/components/widgets/baseWidget.js
=> Remove ocurrences of .bind(this)

src/components/Plotly.vue
=> Add Min/Max/Mean to legends

src/tools/parsers/modeMaps.js
Flight mode definitions updated as per :
https://github.com/ArduPilot/ardupilot/blob/ArduCopter-stable/ArduCopter/mode.h
https://github.com/ArduPilot/ardupilot/blob/plane4.0/ArduPlane/mode.h
https://github.com/ArduPilot/ardupilot/blob/Sub-4.1/ArduSub/defines.h
https://github.com/ArduPilot/ardupilot/blob/Rover-4.0/APMrover2/mode.h
https://github.com/ArduPilot/ardupilot/blob/Tracker-1.1/AntennaTracker/defines.h
Also fixes #263
=> Flight mode definitions updated

src/components/Plotly.vue, src/tools/parsers/dataflashParser.js
=> Deal with isolated instances, deal with failures loading bad messages.

package-lock.json, package.json, src/components/CesiumViewer.vue, src/components/Home.vue
=> Allow running offline

src/tools/mavlinkDataExtractor.js
=> mavlinkDataExtractor: filter for valid vehicles

src/components/Globals.js, src/components/Home.vue, src/components/Sidebar.vue, src/components/widgets/DeviceIDViewer.vue, src/components/widgets/MessageViewer.vue, src/components/widgets/ParamViewer.vue
=> Create DeviceID widget

src/components/CesiumViewer.vue, src/components/Globals.js, src/components/Sidebar.vue
=> Cesium: allow manually changing the altitude offset

src/components/Plotly.vue
=> plotly: filter STAT_FLLTIME and STAT_RUNTIME

package-lock.json, package.json, src/components/CesiumViewer.vue, src/components/Globals.js, src/components/Home.vue, src/components/SideBarFileManager.vue, src/components/Sidebar.vue, src/tools/dataflashDataExtractor.js, src/tools/mavlinkDataExtractor.js, src/tools/parsers/dataflashParser.js, src/tools/parsers/mavlinkParser.js
Allows loading a 1.2gb dataflash file.
No longer extract data on every message
No longer extract all available trajectories by default
do not load position data with granularity higher than 200ms (this may be tweaked in the future)
=> Memory improvements

src/tools/parsers/dataflashParser.js
=> dataflashparser: use transferables to save memory and avoid copies

src/components/Plotly.vue
=> Plotly: add csv exporting capability

src/components/PlotSetup.vue
=> PlotSetup.vue: create 'clear' button

src/components/widgets/TreeMenu.vue
=> TreeMenu.vue: add confirmation dialog when deleting a preset

src/components/CesiumViewer.vue
Fixes doubling of fence radius
=> Fixes fence radius

build/webpack.base.conf.js
=> use file-loader for svgs
