mavlink_common_v1.0/mavlink.js
=> mavlink: filter out messages with no time_boot_ms field

src/components/Plotly.vue
=> Plotly: move legend to graph area, make it draggable

src/components/Plotly.vue
plotly is kinda broken right now in https://tlog.galvanicloop.com. It lets you drag the mode shapes around and the data cursor is not working. this fixes that
=> Plotly: make shapes not editable (remove cursor events)

src/components/CesiumViewer.vue, src/components/Plotly.vue
I managed to get rid of some events, but it is still necessary to force a resize of plotly when disabling cesium, for some reason
=> make plotly and cesium behave properly when each other is disabled

src/components/Globals.js, src/components/Home.vue, src/components/Plotly.vue, src/tools/parsers/dataflashParser.js
this shows when the vehicle was armed/disarmed in the plot:
=> Plotly: add annotations for when vehicle is armed/disarmed

package-lock.json, package.json, src/components/CesiumViewer.vue, src/components/Home.vue, src/components/Plotly.vue
With this, we no longer need that cesium-style flight mode legend over the plot
=> Plotly: encode flight modes in plot

src/components/Plotly.vue
=> Plotly: Copy flight_mode_changes instead of using reference and modifying it

src/components/Plotly.vue
In order to be able to plot constants, the code can fallback to "backup" time scale(ATT or ATTITUDE). This typo was making the code default to that, partially causing #222
=> Plotly: fix typo in evaluateExpression()

src/components/Plotly.vue
Plotting "1+1" crashes without this patch
=> Plotly: fix plotting constants

src/components/CesiumViewer.vue
Mapbox turned out to be pretty expensive. Bing sessions on cesiumjs too.
This changes the default imagery provider to Sentinel, but
the higher resolution providers are
still available via the baselayer selector.
Sentinel-2 is a lower-resolution imagery provider with aggressive local caching.
=> Cesium: make sentinel-2 the default provider for imagery

src/components/CesiumViewer.vue
This was fixed in https://github.com/CesiumGS/cesium/pull/8504
=> Cesium: remove now-useless code that prevented camera from going underground

src/tools/parsers/dataflashParser.js
This makes AHR2 the preferential attitude source
=> dataflashparser.js: move AHR2 parsing to before ATT

src/components/CesiumViewer.vue
Previous behavior was checking all points and making sure nothing goes underground.
That is no longer necessary as we can now make the globe transparent.
Fix #266
=> Cesium: only tie start position to ground height

mavlink_common_v1.0/mavlink.js, src/components/SideBarFileManager.vue, src/components/Sidebar.vue, src/tools/parsers/mavlinkParser.js, src/tools/parsers/parser.worker.js
This allows the user to export the current time-span of the log as a standalone log.
currently only implemented for .tlog files
helps #244
=> Allow downloading trimmed .tlog files

src/components/SideBarFileManager.vue
This will allow it to be embedded in other services, such as the autotest server or companion computers.
=> Allow fetching a remote file with ?file=[url]

src/components/Plotly.vue
=> Plotly: use replaceAll when plotting expressions

src/components/Plotly.vue
=> Plotly.vue: fix re-using object when populating data for expressions

src/components/CesiumViewer.vue, src/components/Globals.js, src/components/Sidebar.vue, src/components/widgets/TxInputs.vue
Many operators in Japan operate their drones in mode 1 of the radio.
The joystick display in UAVLogViewer is in Mode 2.
I have added a setting item to allow selection of mode 1 or 2.
AFTER
MODE 1
MODE2
=> components: Mode 1 and 2 can be specified on the joystick display

src/components/SideBarFileManager.vue
the other side should do something like this:
```
!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>File Loader</title>
</head>
<body>
<input type="file" id="fileInput">
<script>
const fileInput = document.getElementById('fileInput')
fileInput.addEventListener('change', function(event) {
const file = event.target.files[0]
if (file) {
const reader = new FileReader()
reader.onload = function(e) {
const arrayBuffer = e.target.result
// Open the new page and keep a reference to it
const newWindow = window.open('http://localhost:8080')
// Wait a bit to ensure the new page is fully loaded
setTimeout(() => {
// Send the ArrayBuffer to the new window using postMessage
newWindow.postMessage({ type: 'arrayBuffer', data: arrayBuffer }, 'http://localhost:8080')
}, 2000)
} …
```
=> Allow parsing a file from window.postMessage()

README.md
As noticed here https://github.com/ArduPilot/UAVLogViewer/pull/431#issuecomment-2887716161, the docker reference I made in the readme included upper case letters which wrong.
Also the workflow will only upload a docker image to ghcr if you create a release ( a tag with format v.xx).
So it would be good to trigger this once as otherwise there will be no latest image to download.
=> fixed docker reference to be lower case
